#!/usr/bin/env sh
. "$(dirname "$0")/common.sh"

# Verifica se é merge
git merge HEAD &> /dev/null
IS_MERGE_PROCESS=$?

if [ $IS_MERGE_PROCESS -ne 0 ]; then
    exit 0
fi

# Recupera arquivos em staging
STAGED_FILES=$(git diff --cached --name-only)

# Aborta a execução caso a área de staging esteja limpa
if [ -z "$STAGED_FILES" ]; then
    exit 0
fi

# Executa formatação
echo "🔍 Formatando código PHP com Pint..."
run_php vendor/bin/pint

echo "🎨 Formatando código frontend com Prettier..."
npm run prettier

# Re-adiciona arquivos formatados
git add $STAGED_FILES

echo "✅ Código formatado com sucesso!"
